/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Spring (https://sketchfab.com/Springy01)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/batdr-beast-bendy-217351cde3864dd7870c5480b2ec24d0
title: BATDR Beast Bendy
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/demon.gltf')
  return (
    <>
    <group scale={0.13} {...props} dispose={null}>
      <primitive object={nodes.GLTF_created_0_rootJoint} />
      <skinnedMesh
        geometry={nodes.Object_7.geometry}
        material={materials.Skin_1}
        skeleton={nodes.Object_7.skeleton}
      />
    </group>
    <Shadow/>
    </>
  );
}

const Shadow = () => {
  return (
    <group>
      <mesh rotation={[-Math.PI / 2, 0, 0]} position={[-1, 1, 3]}>
        <circleBufferGeometry blur={0.2} attach="geometry" args={[3, 4]} />
        <meshLambertMaterial attach="material" color={"black"} />
      </mesh>
    </group>
  );
};

useGLTF.preload('/demon.gltf')
