/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Spring (https://sketchfab.com/Springy01)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/batdr-beast-bendy-217351cde3864dd7870c5480b2ec24d0
title: BATDR Beast Bendy
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/demon.gltf')
  return (
    <group scale={0.1} {...props} dispose={null}>
          <primitive object={nodes.GLTF_created_0_rootJoint} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Skin_1} skeleton={nodes.Object_7.skeleton} />
    </group>
  )
}

useGLTF.preload('/demon.gltf')
